In [1]:
import pandas as pd
import numpy as np

In [2]:
def make_df(cols, ind):
    """Quickly make a data frame"""
    data = {c: [str(c)+str(i) for i in ind] for c in cols}
    return pd.DataFrame(data, ind)

#example Data Frame
make_df('ABC', range(3))

A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [3]:
class display(object):
    """Display HTML representation of multiple objects"""
    template = """<div style="float: left; padding: 10px;">
    <p style='font-family:"Courier New", Courier, monospace'>{0}</p>{1}
    </div>"""
    def __init__(self, *args):
        self.args = args
        
    def _repr_html_(self):
        return '\n'.join(self.template.format(a, eval(a)._repr_html_())
                         for a in self.args)
    
    def __repr__(self):
        return '\n\n'.join(a + '\n' + repr(eval(a))
                           for a in self.args)
    

Recall: Concatenation of NumPy Arrays

In [4]:
x = [1,2,3]
y = [4,5,6]
z = [7,8,9]
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
x = [[1,2],[3,4]]
np.concatenate([x,x], axis = 1)

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [7]:
np.concatenate([x,x], axis = 0)

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [8]:
np.concatenate([x,x], axis = 1).T

array([[1, 3],
       [2, 4],
       [1, 3],
       [2, 4]])

Simple Concatenation with pd.concat

In [9]:
ser1 = pd.Series(['A','B','C'], index = [1,2,3])
ser2 = pd.Series(['D','E','F'], index = [4,5,6])
pd.concat([ser1,ser2])

1    A
2    B
3    C
4    D
5    E
6    F
dtype: object

In [10]:
np.concatenate(ser1, ser2)

TypeError: 'Series' object cannot be interpreted as an integer

In [14]:
df1 = make_df('AB', [1,2])
df2 = make_df('AB', [3,4])
display('df1','df2', 'pd.concat([df1,df2])')

df1
    A   B
1  A1  B1
2  A2  B2

df2
    A   B
3  A3  B3
4  A4  B4

pd.concat([df1,df2])
    A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4

In [15]:
df1

A   B
1  A1  B1
2  A2  B2

In [16]:
pd.concat([df1,df2])

A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4

In [20]:
df3 = make_df('AB', [0,1])
df4 = make_df('CD', [0,1])
display('df3','df4', "pd.concat([df3, df4], axis=1)")

df3
    A   B
0  A0  B0
1  A1  B1

df4
    C   D
0  C0  D0
1  C1  D1

pd.concat([df3, df4], axis=1)
    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1

In [21]:
display('df3','df4', "pd.concat([df3, df4], axis=0)")

df3
    A   B
0  A0  B0
1  A1  B1

df4
    C   D
0  C0  D0
1  C1  D1

pd.concat([df3, df4], axis=0)
     A    B    C    D
0   A0   B0  NaN  NaN
1   A1   B1  NaN  NaN
0  NaN  NaN   C0   D0
1  NaN  NaN   C1   D1

Duplicate indices

In [22]:
x = make_df('AB', [0,1])
y = make_df('AB', [2,3])
y.index = x.index
display('x', 'y', 'pd.concat([x,y])')

x
    A   B
0  A0  B0
1  A1  B1

y
    A   B
0  A2  B2
1  A3  B3

pd.concat([x,y])
    A   B
0  A0  B0
1  A1  B1
0  A2  B2
1  A3  B3

In [23]:
try:
    pd.concat([x, y], verify_integrity=True)
except ValueError as e:
    print("ValueError:", e)

ValueError: Indexes have overlapping values: Int64Index([0, 1], dtype='int64')


Ignoring the index

In [24]:
display('x', 'y', 'pd.concat([x, y], ignore_index=True)')

x
    A   B
0  A0  B0
1  A1  B1

y
    A   B
0  A2  B2
1  A3  B3

pd.concat([x, y], ignore_index=True)
    A   B
0  A0  B0
1  A1  B1
2  A2  B2
3  A3  B3

Adding MultiIndex keys

In [25]:
display('x', 'y', "pd.concat([x, y], keys=['x', 'y'])")

x
    A   B
0  A0  B0
1  A1  B1

y
    A   B
0  A2  B2
1  A3  B3

pd.concat([x, y], keys=['x', 'y'])
      A   B
x 0  A0  B0
  1  A1  B1
y 0  A2  B2
  1  A3  B3

Concatenation with joins

In [26]:
df5 = make_df('ABC', [1,2])
df6 = make_df('BCD', [3,4])
display('df5', 'df6', 'pd.concat([df5,df6])')

df5
    A   B   C
1  A1  B1  C1
2  A2  B2  C2

df6
    B   C   D
3  B3  C3  D3
4  B4  C4  D4

pd.concat([df5,df6])
     A   B   C    D
1   A1  B1  C1  NaN
2   A2  B2  C2  NaN
3  NaN  B3  C3   D3
4  NaN  B4  C4   D4

In [27]:
display('df5', 'df6', "pd.concat([df5,df6],join = 'inner')")

df5
    A   B   C
1  A1  B1  C1
2  A2  B2  C2

df6
    B   C   D
3  B3  C3  D3
4  B4  C4  D4

pd.concat([df5,df6],join = 'inner')
    B   C
1  B1  C1
2  B2  C2
3  B3  C3
4  B4  C4

In [29]:
display('df5', 'df6', "pd.concat([df5, df6], join_axes=[df5.columns])")

TypeError: concat() got an unexpected keyword argument 'join_axes'

TypeError: concat() got an unexpected keyword argument 'join_axes'

The append() method

In [30]:
display('df1', 'df2', 'df1.append(df2)')

df1
    A   B
1  A1  B1
2  A2  B2

df2
    A   B
3  A3  B3
4  A4  B4

df1.append(df2)
    A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4

In [31]:
pd.concat([df1,df2])

A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4